### ISSUE TITLE
OSS Licensing Clarification

### ISSUE THREAD

**Issue by mrvaghani** [jensim/sourcegraph-release-train#1]
Hello, I really like your [sourcegraph-server-oss](https://hub.docker.com/r/jensim/sourcegraph-server-oss) image but I am having difficulty understanding the license model for sourcegraph and I was hoping you might be able to shed some light.

Your image seems to have some [license](https://github.com/jensim/sourcegraph-release-train/blob/main/mod/license.txt) files and some of the [files under the enterprise folder](https://github.com/jensim/sourcegraph-release-train/blob/main/mod/train-mod.bash#L58). But your readme says the pipeline is for the OSS version.

If you can update the documentation to clarify the licensing, that would be extremely helpful.

**Comment by jensim** [comment]
Yea - that was a little pen-test that I ran on the source-code, to see IF someone was to substitute the baked in license with some known secret, and run that instead, how difficult that would be.. But my time cap that I set ended, so I dropped it..

**Comment by mrvaghani** [comment]
Ah nice test! I was very confused at first but I thought that's what you had used in the docker image. I read your comment on the other thread about your container not using the enterprise files. Is there any chance you would be down to build up a docker compose file that we can use on a fork of the original repo? I know it's not exactly automated like you have it right now but it would definitely provide more visibility into how/what code gets added to the container.

**Comment by jensim** [comment]
I have too much oss ownership to add more maintenance debt at thos point in time.. So if i were to create something that doesn't maintain itself, it might just lie and gather dust ☹️
The steps to reproduce the release train are all gathered in the train.bash file, maybe i could collect that in himan readable form in markdown..?

**Comment by mrvaghani** [comment]
Fair enough. And yeah, I think maybe a markdown version explaining pieces of code might be helpful. Thanks! In the meantime, I plan on going through sourcegraph's build.sh to understand the actual build process.

**Comment by jensim** [comment]
There is good dev docs in sourcegraph repo 🥳👍
And that's how I created my build script! 
Which is fairly short imho 🤷 aaaalmost human readable, it's bash, so just add a few comments, and it's like the invert of markdown 😅
