### ISSUE TITLE
Patches required to get 4.1.2 working

### ISSUE THREAD

**Issue by simhnna** [jensim/sourcegraph-release-train#3]
Hi there.
Thanks very much for your effort. I used your code as a starting point for my own version of sourcegraph.

Just wanted to let you know that I had to apply some patches to get the popup and reference search to work.
https://github.com/simhnna/sourcegraph-release-train/blob/dev-patches/patches/gql.patch
https://github.com/simhnna/sourcegraph-release-train/blob/dev-patches/patches/type.patch

I've created a merge request for the type.patch in the sourcegraph repo. The gql patch will definitely break the enterprise version, but works fine for the oss version. You're welcome to use them if you want

**Comment by jensim** [comment]
Thank you 👍
I'm not running the enterprise version, and don't intend to 🤷
But thanks for wanting to contribute!
