### ISSUE TITLE
Sourcegraph OSS has been eliminated

### ISSUE THREAD

**Issue by grrttedwards** [jensim/sourcegraph-release-train#5]
Hello. Word of warning, this project built Sourcegraph tag 5.1.0, in which they just eliminated OSS entirely and all code falls under their enterprise license. What a shock...

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#5-1-0

> Note: As of 5.1.0, Sourcegraph OSS is removed and has been relicensed to Sourcegraph Enterprise. A blog post with much more detail will come soon!

PR if you were interested: https://github.com/sourcegraph/sourcegraph/commit/3cd931ef54407c966fc3a5940a06f0b95a7aadd0

**Comment by jensim** [comment]
Thanks @grrttedwards! I'll need to stop this train then..
It's been running itself for a long time. Feels a bit dark to stop it.
